class ExampleCtrl(object):
    """Mealy transducer.

    Internal states are integers, the current state
    is stored in the attribute "state".
    To take a transition, call method "move".

    The names of input variables are stored in the
    attribute "input_vars".

    Automatically generated by tulip.dumpsmach on 2019-10-06 07:38:58 UTC
    To learn more about TuLiP, visit http://tulip-control.org
    """
    def __init__(self):
        self.state = 24
        self.input_vars = ['requested', 'clear']

    def move(self, requested, clear):
        """Given inputs, take move and return outputs.

        @rtype: dict
        @return: dictionary with keys of the output variable names:
            ['leave', 'at_P1', 'at_pick_up', 'at_drop_off', 'driving_to_leave', 'at_entrance', 'loc']
        """
        output = dict()
        if self.state == 0:
            if (clear == False) and (requested == False):
                self.state = 0

                output["at_P1"] = False
                output["at_drop_off"] = True
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X0'
            elif (clear == True) and (requested == False):
                self.state = 1

                output["at_P1"] = False
                output["at_drop_off"] = True
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X0'
            elif (clear == False) and (requested == True):
                self.state = 2

                output["at_P1"] = False
                output["at_drop_off"] = True
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X0'
            elif (clear == True) and (requested == True):
                self.state = 3

                output["at_P1"] = False
                output["at_drop_off"] = True
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X0'
            else:
                self._error(requested, clear)
        elif self.state == 1:
            if (clear == False) and (requested == False):
                self.state = 4

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = True
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X1'
            elif (clear == True) and (requested == False):
                self.state = 5

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = True
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X1'
            elif (clear == False) and (requested == True):
                self.state = 6

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = True
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X1'
            elif (clear == True) and (requested == True):
                self.state = 7

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = True
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X1'
            else:
                self._error(requested, clear)
        elif self.state == 2:
            if (clear == False) and (requested == False):
                self.state = 0

                output["at_P1"] = False
                output["at_drop_off"] = True
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X0'
            elif (clear == True) and (requested == False):
                self.state = 1

                output["at_P1"] = False
                output["at_drop_off"] = True
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X0'
            elif (clear == False) and (requested == True):
                self.state = 2

                output["at_P1"] = False
                output["at_drop_off"] = True
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X0'
            elif (clear == True) and (requested == True):
                self.state = 3

                output["at_P1"] = False
                output["at_drop_off"] = True
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X0'
            else:
                self._error(requested, clear)
        elif self.state == 3:
            if (clear == False) and (requested == False):
                self.state = 4

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = True
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X1'
            elif (clear == True) and (requested == False):
                self.state = 5

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = True
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X1'
            elif (clear == False) and (requested == True):
                self.state = 6

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = True
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X1'
            elif (clear == True) and (requested == True):
                self.state = 7

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = True
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X1'
            else:
                self._error(requested, clear)
        elif self.state == 4:
            if (clear == False) and (requested == False):
                self.state = 4

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = True
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X1'
            elif (clear == True) and (requested == False):
                self.state = 5

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = True
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X1'
            elif (clear == False) and (requested == True):
                self.state = 6

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = True
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X1'
            elif (clear == True) and (requested == True):
                self.state = 7

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = True
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X1'
            else:
                self._error(requested, clear)
        elif self.state == 5:
            if (clear == False) and (requested == False):
                self.state = 8

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            elif (clear == True) and (requested == False):
                self.state = 9

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            elif (clear == False) and (requested == True):
                self.state = 10

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            elif (clear == True) and (requested == True):
                self.state = 11

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            else:
                self._error(requested, clear)
        elif self.state == 6:
            if (clear == False) and (requested == False):
                self.state = 4

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = True
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X1'
            elif (clear == True) and (requested == False):
                self.state = 5

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = True
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X1'
            elif (clear == False) and (requested == True):
                self.state = 6

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = True
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X1'
            elif (clear == True) and (requested == True):
                self.state = 7

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = True
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X1'
            else:
                self._error(requested, clear)
        elif self.state == 7:
            if (clear == False) and (requested == False):
                self.state = 8

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            elif (clear == True) and (requested == False):
                self.state = 9

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            elif (clear == False) and (requested == True):
                self.state = 10

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            elif (clear == True) and (requested == True):
                self.state = 11

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            else:
                self._error(requested, clear)
        elif self.state == 8:
            if (clear == False) and (requested == False):
                self.state = 8

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            elif (clear == True) and (requested == False):
                self.state = 9

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            elif (clear == False) and (requested == True):
                self.state = 10

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            elif (clear == True) and (requested == True):
                self.state = 11

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            else:
                self._error(requested, clear)
        elif self.state == 9:
            if (clear == False) and (requested == False):
                self.state = 8

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            elif (clear == True) and (requested == False):
                self.state = 9

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            elif (clear == False) and (requested == True):
                self.state = 10

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            elif (clear == True) and (requested == True):
                self.state = 11

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            else:
                self._error(requested, clear)
        elif self.state == 10:
            if (clear == False) and (requested == False):
                self.state = 8

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            elif (clear == True) and (requested == False):
                self.state = 9

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            elif (clear == False) and (requested == True):
                self.state = 10

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            elif (clear == True) and (requested == True):
                self.state = 11

                output["at_P1"] = True
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'P1'
            else:
                self._error(requested, clear)
        elif self.state == 11:
            if (clear == False) and (requested == False):
                self.state = 12

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = True
                output["leave"] = False
                output["loc"] = 'X7'
            elif (clear == True) and (requested == False):
                self.state = 13

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = True
                output["leave"] = False
                output["loc"] = 'X7'
            elif (clear == False) and (requested == True):
                self.state = 14

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = True
                output["leave"] = False
                output["loc"] = 'X7'
            elif (clear == True) and (requested == True):
                self.state = 15

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = True
                output["leave"] = False
                output["loc"] = 'X7'
            else:
                self._error(requested, clear)
        elif self.state == 12:
            if (clear == False) and (requested == False):
                self.state = 12

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = True
                output["leave"] = False
                output["loc"] = 'X7'
            elif (clear == True) and (requested == False):
                self.state = 13

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = True
                output["leave"] = False
                output["loc"] = 'X7'
            elif (clear == False) and (requested == True):
                self.state = 14

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = True
                output["leave"] = False
                output["loc"] = 'X7'
            elif (clear == True) and (requested == True):
                self.state = 15

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = True
                output["leave"] = False
                output["loc"] = 'X7'
            else:
                self._error(requested, clear)
        elif self.state == 13:
            if (clear == False) and (requested == False):
                self.state = 16

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = True
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X9'
            elif (clear == True) and (requested == False):
                self.state = 17

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = True
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X9'
            elif (clear == False) and (requested == True):
                self.state = 18

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = True
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X9'
            elif (clear == True) and (requested == True):
                self.state = 19

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = True
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X9'
            else:
                self._error(requested, clear)
        elif self.state == 14:
            if (clear == False) and (requested == False):
                self.state = 12

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = True
                output["leave"] = False
                output["loc"] = 'X7'
            elif (clear == True) and (requested == False):
                self.state = 13

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = True
                output["leave"] = False
                output["loc"] = 'X7'
            elif (clear == False) and (requested == True):
                self.state = 14

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = True
                output["leave"] = False
                output["loc"] = 'X7'
            elif (clear == True) and (requested == True):
                self.state = 15

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = True
                output["leave"] = False
                output["loc"] = 'X7'
            else:
                self._error(requested, clear)
        elif self.state == 15:
            if (clear == False) and (requested == False):
                self.state = 16

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = True
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X9'
            elif (clear == True) and (requested == False):
                self.state = 17

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = True
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X9'
            elif (clear == False) and (requested == True):
                self.state = 18

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = True
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X9'
            elif (clear == True) and (requested == True):
                self.state = 19

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = True
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X9'
            else:
                self._error(requested, clear)
        elif self.state == 16:
            if (clear == False) and (requested == False):
                self.state = 16

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = True
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X9'
            elif (clear == True) and (requested == False):
                self.state = 17

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = True
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X9'
            elif (clear == False) and (requested == True):
                self.state = 18

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = True
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X9'
            elif (clear == True) and (requested == True):
                self.state = 19

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = True
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X9'
            else:
                self._error(requested, clear)
        elif self.state == 17:
            if (clear == False) and (requested == False):
                self.state = 20

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            elif (clear == True) and (requested == False):
                self.state = 21

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            elif (clear == False) and (requested == True):
                self.state = 22

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            elif (clear == True) and (requested == True):
                self.state = 23

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            else:
                self._error(requested, clear)
        elif self.state == 18:
            if (clear == False) and (requested == False):
                self.state = 16

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = True
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X9'
            elif (clear == True) and (requested == False):
                self.state = 17

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = True
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X9'
            elif (clear == False) and (requested == True):
                self.state = 18

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = True
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X9'
            elif (clear == True) and (requested == True):
                self.state = 19

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = True
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X9'
            else:
                self._error(requested, clear)
        elif self.state == 19:
            if (clear == False) and (requested == False):
                self.state = 20

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            elif (clear == True) and (requested == False):
                self.state = 21

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            elif (clear == False) and (requested == True):
                self.state = 22

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            elif (clear == True) and (requested == True):
                self.state = 23

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            else:
                self._error(requested, clear)
        elif self.state == 20:
            if (clear == False) and (requested == False):
                self.state = 20

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            elif (clear == True) and (requested == False):
                self.state = 21

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            elif (clear == False) and (requested == True):
                self.state = 22

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            elif (clear == True) and (requested == True):
                self.state = 23

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            else:
                self._error(requested, clear)
        elif self.state == 21:
            if (clear == False) and (requested == False):
                self.state = 20

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            elif (clear == True) and (requested == False):
                self.state = 21

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            elif (clear == False) and (requested == True):
                self.state = 22

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            elif (clear == True) and (requested == True):
                self.state = 23

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            else:
                self._error(requested, clear)
        elif self.state == 22:
            if (clear == False) and (requested == False):
                self.state = 20

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            elif (clear == True) and (requested == False):
                self.state = 21

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            elif (clear == False) and (requested == True):
                self.state = 22

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            elif (clear == True) and (requested == True):
                self.state = 23

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            else:
                self._error(requested, clear)
        elif self.state == 23:
            if (clear == False) and (requested == False):
                self.state = 20

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            elif (clear == True) and (requested == False):
                self.state = 21

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            elif (clear == False) and (requested == True):
                self.state = 22

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            elif (clear == True) and (requested == True):
                self.state = 23

                output["at_P1"] = False
                output["at_drop_off"] = False
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = True
                output["loc"] = 'X11'
            else:
                self._error(requested, clear)
        elif self.state == 24:
            if (clear == False) and (requested == False):
                self.state = 0

                output["at_P1"] = False
                output["at_drop_off"] = True
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X0'
            elif (clear == True) and (requested == False):
                self.state = 1

                output["at_P1"] = False
                output["at_drop_off"] = True
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X0'
            elif (clear == False) and (requested == True):
                self.state = 2

                output["at_P1"] = False
                output["at_drop_off"] = True
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X0'
            elif (clear == True) and (requested == True):
                self.state = 3

                output["at_P1"] = False
                output["at_drop_off"] = True
                output["at_entrance"] = False
                output["at_pick_up"] = False
                output["driving_to_leave"] = False
                output["leave"] = False
                output["loc"] = 'X0'
            else:
                self._error(requested, clear)
        else:
            raise Exception("Unrecognized internal state: " + str(self.state))
        return output

    def _error(self, requested, clear):
        raise ValueError("Unrecognized input: " + (
            "requested = {requested}; "
            "clear = {clear}; ").format(
                requested=requested,
                clear=clear))
